# Generated by Django 4.2.7 on 2023-11-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_distancemeasurement_delete_item_delete_todolist"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrashCan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="trash_can",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.trashcan",
            ),
        ),
    ]
